#!/usr/bin/python

import getpass
import os

username = raw_input("Enter Your Way2SMS username: ")
password = getpass.getpass("Enter Your Way2SMS password: ")

def createfile(uname,pwd):
	home = os.popen("echo $HOME").read()
	home = home.strip('\n')
	f = open(home+'/.login','w+')
	f.write(uname + "\n" + pwd)
	f.close()

createfile(username,password)
print "Login Details saved in a hidden file named .login in your Home directory"
